using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using WarehouseService;

namespace ST4_ImplementationExamples
{
    public class SOAP
    {
        public SOAP()
        {
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        //runner
        public async Task RunExample()
        {
            
        }
        public async void GetStatus()
        {
            var service = new EmulatorServiceClient();
            var response = await service.GetInventoryAsync();
            Console.WriteLine(response);
        }

        public async void PickSingleItem()
        {
            var service = new EmulatorServiceClient();
            Console.WriteLine("Input Item Number:");
            int pickItemNum = Convert.ToInt32(Console.ReadLine());
            var pickRe = await service.PickItemAsync(pickItemNum);
            Console.WriteLine(pickRe);
        }

        public async void InsertSingleItem()
        {
            var service = new EmulatorServiceClient();
            Console.WriteLine("Input Item to Insert & Name");
            int insertNum = Convert.ToInt32(Console.ReadLine());
            string insertName = Convert.ToString(Console.ReadLine());
            var insertRe = await service.InsertItemAsync(insertNum, insertName);
            Console.WriteLine(insertRe);

        }


        private int itemNum = 0;
        public async void PickAndInsertItem()
        {
            var service = new EmulatorServiceClient();
            
            var name = "Inserted";
            
            itemNum = itemNum + 1;
            if (itemNum > 10)
            {
                itemNum = 1;
            }
            
            
            Console.WriteLine("Item number and name inserted: " + itemNum + " " + name);
            var pickInsertPick = await service.PickItemAsync(itemNum);
            var pickInsertItem = await service.InsertItemAsync(itemNum, name);
            Console.WriteLine(pickInsertPick + " & " + pickInsertItem);
        }
    }
}